name: Python package

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch
  pull_request:
    branches:
      - main  # Runs on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can change this to the appropriate OS if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies listed in requirements.txt

    - name: Run tests
      run: |
        pytest  # Replace this with your testing framework/commands

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel  # Build your package

    - name: Upload to PyPI (Optional)
      if: github.ref == 'refs/heads/main'  # Only upload to PyPI when pushing to the main branch
      uses: pypa/gh-action-pypi-publish@v1.4.0  # Action to upload to PyPI
      with:
        user: ${{ secrets.PYPI_USERNAME }}  # Store PyPI username as a secret
        password: ${{ secrets.PYPI_PASSWORD }}  # Store PyPI password as a secret
